Migrate to GitHub Actions
dart-lang/characters pull request #44
Opened 2020-12-21 13:30 UTC by athomas

2020-12-21 21:39 UTC, kevmoo commented on README.md
> +[![Build Status](https://github.com/dart-lang/characters/workflows/Dart%20CI/badge.svg)](https://github.com/dart-lang/characters/actions?query=workflow%3A"Dart+CI")
link to master branch!

2020-12-21 21:39 UTC, kevmoo requested changes
link to the master branch in the badge

2021-01-12 17:03 UTC, athomas commented on README.md
> +[![Build Status](https://github.com/dart-lang/characters/workflows/Dart%20CI/badge.svg)](https://github.com/dart-lang/characters/actions?query=workflow%3A"Dart+CI")
Done

2021-01-12 17:06 UTC, kevmoo approved these changes

2021-01-12 17:10 UTC, merged